---
- hosts: web
  gather_facts: false
  vars:
   - app_name: yum
  tasks:
#   - name: copy script from local to remote machine
#     copy: src=/root/ishank_ansible/script.sh dest=/root
   - name: removing the cron
     cron:
         name: "to run the script"
         state: absent
